### ISSUE TITLE
Not compatible with ARM

### ISSUE THREAD

**Issue by aussiehash** [LedgerHQ/ledger-app-builder#1]
I've tried this docker on a Pi4b with manjaro and raspian.

The docker fails on the wheel build, and if commented out, the multilib libraries are not available on apt for ARM

I was able to build it on Ubuntu AMD64, but my compatibility test with app-revealer failed

https://github.com/LedgerHQ/app-revealer/issues/3

**Comment by grydz** [comment]
Unfortunately the [app-revealer](https://github.com/LedgerHQ/app-revealer) does not compile at all with the Nano S SDK 1.6.0.

But you can modify the `Dockerfile` and clone the Nano S SDK 1.4.2.3 instead. Just replace this [line](https://github.com/LedgerHQ/ledger-app-builder/blob/master/Dockerfile#L33) with:

```
# Nano S SDK
RUN git clone --branch nanos-1423 https://github.com/LedgerHQ/nanos-secure-sdk.git sdk
```
then

```
$ docker build -t ledger-app-builder:1.4.2.3 .
```

finally don't forget to add `CFLAGS=-I/usr/include` when you compile (only necessary for old SDK):

```
# CFLAGS=-I/usr/include make
```

**Comment by aussiehash** [comment]
Thank you for the tip,

I have now been able to successfully build the `app-revealer` in the Docker container by modifying the Dockerfile,  
`docker build -t ledger-app-builder:1.4.2.3 .`
`cd ../app-revealer`
`sudo docker run -ti -v $(realpath .):/app ledger-app-builder:1.4.2.3`
`CFLAGS=-I/usr/include make`

However when I try `make all load` it produces the error

```
> # CFLAGS=-I/usr/include make load
> TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100003
> BOLOS_ENV=/compilers
> python -m ledgerblue.loadApp --appFlags 0x10 --tlv --targetId 0x31100003 --delete --fileName bin/app.hex --appName "Revealer" --appVersion 1.0.1 --dataSize `cat debug/app.map |grep _nvram_data_size | tr -s ' ' | cut -f2 -d' '` `ICONHEX=\`python /sdk/icon.py icon.gif hexbitmaponly 2>/dev/null\` ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"`  --apdu --curve secp256k1 --path ""
> Generated random root public key : b'04923a847430968918ade801c4cb9a7f8afc10e3592b0d49ef60b7f8873c3d2e006b394789bb71b5010a96783792f6aa5e29d20a3a5b903a4bb88d94417b58b819'
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.8/site-packages/ledgerblue/loadApp.py", line 197, in <module>
>     dongle = getDongle(args.apdu)
>   File "/usr/local/lib/python3.8/site-packages/ledgerblue/comm.py", line 240, in getDongle
>     raise CommException("No dongle found")
> ledgerblue.commException.CommException: Exception : No dongle found
> make: *** [Makefile:69: load] Error 1
```

I have never been able to run an installed app on my NanoS, either the `/bin/app.hex` I've just built, or the old beta release of app-revealer on github.

I must be doing something wrong, I've tried a combination of 
`$ python3 -m ledgerblue.loadApp --curve secp256k1 --tlv --targetId 0x31100004 --delete --fileName app.hex --appName "Revealer" --appVersion 1.0.1`

```
> Generated random root public key : b'044cd942324ca42abcffd6b2d178474af2714cb44eea89d15ec2f977d1d712dd280cda04a19c1cb6f73689b780df1a9c0b1111dd0f7a6551f64246637dcfe4a246'
> Using test master key b'044cd942324ca42abcffd6b2d178474af2714cb44eea89d15ec2f977d1d712dd280cda04a19c1cb6f73689b780df1a9c0b1111dd0f7a6551f64246637dcfe4a246' 
> Using ephemeral key b'04f8def8c1a17935892c84fe3f638a18333bf3bf3a4aa8dbb57bca43915eef6c875ad7e8b0a3e8b93bbdc91581ae9a1b8503f0b33155586a6164c4cd2bdc526ea2'
> Broken certificate chain - loading from user key
> Target version is not set, application hash will not match!
> Application full hash : 4f15f14f47ad274eb6f08ed2ff89e4111fba1a610bc11eb0d8de1b878d53749d
```

and other combinations like 
`$ python3 -m ledgerblue.loadApp --curve secp256k1 --tlv --targetId 0x31100004 --delete --fileName app.hex --appName "Revealer" --appVersion 1.0.1 --signApp --signPrivateKey d25a3ac358006222216f0cd408cf37ff35c8bf48e76114d4a2a85896f2216b59`

The app.hex "revealer" does install successfully on the NanoS, but when I try to run it, the NanoS hangs on the "Open non genuine app" screen.

Presumably I need to create a certificate chain, sign the app.hex, and set a target version ?

How do I do that please ?

At least I am able to  `$ python3 -m ledgerblue.deleteApp --targetId 0x31100004 --appName "Revealer"`
```
> Generated random root public key : b'04b3ce5cd00bab649f07959a2318c626f14096988ff93e7ed33c3d719cdaf9fde1a60780225c10ec116d4d786df345a7a556c9b9e1160e6f8362f31634d90a71bc'
> Using test master key b'04b3ce5cd00bab649f07959a2318c626f14096988ff93e7ed33c3d719cdaf9fde1a60780225c10ec116d4d786df345a7a556c9b9e1160e6f8362f31634d90a71bc' 
> Using ephemeral key b'04bc137e45a41cd65b966cd7e9925bfaabc8e8127532a1b0afe1c58560cf7181389cc6e0d80617c8ac5805344caddeed86ff0c3fac8d0314490aaa49b462cc0cfc'
> Broken certificate chain - loading from user key
```

**Comment by grydz** [comment]
It should be feasible to do that by running a privileged container with USB devices mounted:

```
sudo docker run -ti --privileged -v /dev/bus/usb:/dev/bus/usb -v (realpath .):/app ledger-app-builder:1.6.0
```

Note that `ledger-app-builder` is not intended to do that yet and it's not safe to run a privileged container.

**Comment by grydz** [comment]
Closing the issue.

Don't hesitate to open a new one if needed.
