### ISSUE TITLE
Rust compilation no more supported on Alpine 3:15 from nightly-2024-03-02

### ISSUE THREAD

**Issue by yogh333** [LedgerHQ/ledger-app-builder#112]
Starting from `nightly` version `nightly-2024-03-02`, both `rustc` and `cargo` binaries will fail with the following error message:
````
Error relocating /opt/rustup/toolchains/nightly-aarch64-unknown-linux-musl/bin/cargo: pthread_getname_np: symbol not found
````

See https://github.com/rust-lang/rust/issues/121980 for more information.

There is a requirement for musl targets to use musl 1.2.3 (see https://github.com/rust-lang/compiler-team/issues/572)
Alpine 3:15 is using musl `1.2.2` 

One possible solution would be to upgrade Alpine version but it could trigger other side effects.

**Comment by lpascal-ledger** [comment]
Upgrading the Alpine version **will** trigger side effects, however it feels like the most sensible thing to do. Do you have more input on this @apaillier-ledger ?

We should try and save some time to do this. Do you have a deadline linked with this issue @yogh333 ?

**Comment by apaillier-ledger** [comment]
It would bring a newer toolchain, with possible side-effects. But if we're going to do an upgrade like this, might as well move over to a Debian-based image like I tried a few months ago, to have better compatibility and finally get rid of the -legacy container. :+1:

**Comment by yogh333** [comment]
yes I think that using a Debian based image is a better and future proof solution.

**Comment by yogh333** [comment]
Good catch, it looks like it has been fixed.
I close the issue.
