### ISSUE TITLE
'bits/libc-header-start.h' file not found

### ISSUE THREAD

**Issue by florent-uzio** [LedgerHQ/ledger-app-builder#35]
Hi,

I built the docker image of `ledger-app-builder` on my M1 Mackbook pro 14'.
I want to build the XRP app to load it in the Speculos emulator to then be able to run E2E tests in my React app (if that's a wrong approach please let me know).

After building the `ledger-app-builder` Docker image, I ran the command indicated in your Readme:
`docker run --rm -ti -v "$(realpath .):/app" ledger-app-builder:latest` (I replaced `$(realpath .)` by the path to the xrp-app on my Mac).

Then when I run the `make` command I get the following error `'bits/libc-header-start.h' file not found`:

```
root@8d837456c93a:/app# make
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=2.1.0
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
BOLOS_ENV is not set: falling back to CLANGPATH and GCCPATH
CLANGPATH is not set: clang will be used from PATH
GCCPATH is not set: arm-none-eabi-* will be used from PATH
BOLOS_ENV is not set: falling back to CLANGPATH and GCCPATH
CLANGPATH is not set: clang will be used from PATH
GCCPATH is not set: arm-none-eabi-* will be used from PATH
Prepare directories
[CC]   obj/address_ui.o
In file included from src/ui/address/address_ui.c:18:
In file included from /opt/nanos-secure-sdk/include/os_io_seproxyhal.h:29:
In file included from /opt/nanos-secure-sdk/include/os_print.h:3:
/usr/include/stdio.h:27:10: fatal error: 'bits/libc-header-start.h' file not found
#include <bits/libc-header-start.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [/opt/nanos-secure-sdk/Makefile.rules_generic:60: obj/address_ui.o] Error 1
```

Do you have any solution to this?
Thank you

**Comment by florent-uzio** [comment]
To fix it I used this branch:

https://github.com/mandrean/ledger-app-builder/tree/feat/multiarch-amd64-arm64

I built the image with `docker build -t ledger-app-builder:arm64 .` (replace `arm64` by whatever makes sense to you)

Then I ran the container with:
`docker run --rm -ti -v ~/my/path/to/app-xrp:/app ledger-app-builder:arm64`

And then I could successfully build the xrp app `.elf` with the `$NANOX_SDK make` command.

It might be good to merge the branch from `mandrean` but I will let the Ledger team decide.

**Comment by sanglt1902** [comment]
> To fix it I used this branch:
> 
> https://github.com/mandrean/ledger-app-builder/tree/feat/multiarch-amd64-arm64
> 
> I built the image with `docker build -t ledger-app-builder:arm64 .` (replace `arm64` by whatever makes sense to you)
> 
> Then I ran the container with: `docker run --rm -ti -v ~/my/path/to/app-xrp:/app ledger-app-builder:arm64`
> 
> And then I could successfully build the xrp app `.elf` with the `BOLOS_SDK=$NANOX_SDK make` command.
> 
> It might be good to merge the branch from `mandrean` but I will let the Ledger team decide.

That's awesome 👏 , it helps me can build .elf file from m1

**Comment by apaillier-ledger** [comment]
This should be fixed with #36, let us know if you still encounter this issue with the latest version of the containers.

**Comment by florent-uzio** [comment]
Thank you.
I am not using it at the moment but I will let you know if the issue is fixed next time I use it (and if the issue is still open).

**Comment by lpascal-ledger** [comment]
Hello @florent-uzio, could this issue be closed?

**Comment by florent-uzio** [comment]
Hi @lpascal-ledger , I haven't tested it. I suppose we can close it and if another problem happens, we can open a new issue.

**Comment by lpascal-ledger** [comment]
Alright, or reopen this one. Thanks @florent-uzio
